# Generated by Django 3.1.6 on 2021-03-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cityName',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='houseN0',
            new_name='street',
        ),
    ]
